### ISSUE TITLE
Error building SitemapStream in Strapi Sitemap Plugin after removing locale

### ISSUE THREAD

**Issue by princeisamaliya** [pluginpal/strapi-plugin-sitemap#168]
## Bug report
I am using the Strapi sitemap plugin and encountered an error when trying to build the SitemapStream. Initially, I cloned the Strapi starter with Next.js 13, Tailwind, and TypeScript from [this repository](https://strapi.io/blog/introducing-the-new-strapi-starter-with-nextjs13-tailwind-and-typescript). After cloning, I made a modification by removing the locale field. However, I now face the following error specifically when the sitemap tries to include the page collection:

`

> error: [strapi-plugin-sitemap]: Something went wrong while trying to build the SitemapStream. SqliteError: select `t0`.`id`, `t0`.`slug`, `t0`.`locale`, `t0`.`updated_at` from `pages` as `t0` where (((`t0`.`sitemap_exclude` is null) or (`t0`.`sitemap_exclude` = false)) and `t0`.`published_at` is not null) limit 5000 - no such column: t0.locale

`

It seems the plugin is attempting to access the locale column, which no longer exists in my database schema. Unfortunately, I am unable to provide detailed steps to reproduce the error from a fresh start since I am not sure at which point the issue could be reliably reproduced starting from a new project setup.

Any guidance or fix for this issue would be greatly appreciated. Thank you for your help!
### System

- Node.js version: 
- NPM version: 20
- Strapi version: 4.20.4
- Plugin version: 3.1.1
- Database: sqlite
- Operating system: All

**Comment by boazpoolman** [comment]
Hi @princeisamaliya 

Thank you for reporting this issue.
Could you paste the `plugin_sitemap_settings` JSON from the `strapi_core_store_settings` table in your DB?
That will help us to pin-point the issue!

**Comment by princeisamaliya** [comment]
Hi @boazpoolman ,
I have tried to connect with Strapi for DB access, but it can not be shared when you use Strapi cloud hosting. Is there any other way that i can help you with?

**Comment by boazpoolman** [comment]
You could retrieve the core_store settings like this:

1. Go to the sitemap settings page in your admin panel
2. Open your network inspector
3. Find the request to http://localhost:1337/sitemap/settings/
4. Copy it's response and paste it in this issue.

**Comment by boazpoolman** [comment]
I'm going to close this issue due to inactivity.

@princeisamaliya If you still encounter the problem, or have the steps to reproduce it, feel free to re-open the issue.
