### ISSUE TITLE
[FEAT] Wildcard for language in multilanguage sitemap patterns

### ISSUE THREAD

**Issue by SalahAdDin** [pluginpal/strapi-plugin-sitemap#169]
### Summary
We suggest adding a wildcard for languages in the sitemap URL patterns configuration.

### Why is it needed?
Maybe it is not clear in the documentation, but now we can either create a global or language-per-language pattern.

In case we choose the global pattern it will be like: ``/en/posts/[slug]` where `en` is the default language.

Using a wildcard/field on the pattern gives an issue now:
![image](https://github.com/pluginpal/strapi-plugin-sitemap/assets/5034215/89d4bf9c-21cf-4ff8-80ee-040028a39f8d)

![image](https://github.com/pluginpal/strapi-plugin-sitemap/assets/5034215/c258e6d9-b9aa-4a26-b3d2-446c4303218e)

The other alternative is stating parameter language by language, but if the site has more than five languages, it will become a big annoying issue.

### Suggested solution(s)
So, either making it clear in the documentation or enabling the `[lang]` field to be used as a wildcard will improve a lot the developer experience with this wonderful plugin.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request.

**Comment by boazpoolman** [comment]
Hi @SalahAdDin 

Thanks for reporting yet another great feature request!
You really help us push our plugins to the next level.

About the sitemap plugin; we are currently in the process of migrating the plugin to the [Webtools suite](https://github.com/pluginpal/strapi-webtools).
Just now I've released the first beta version of the [Webtools Sitemap Addon to NPM](https://www.npmjs.com/package/@pluginpal/webtools-addon-sitemap)
It has all the same features you're used to from the standalone Sitemap plugin, but uses the core Webtools plugin for it's URL management.

The issue you created about the "Wildcard for language" is a feature that's already integrated in Webtools.
That being said I would love it if you could give Webtools and the Sitemap addon a try. I think you'll like it a lot.

**Comment by SalahAdDin** [comment]
> Hi @SalahAdDin
> 
> Thanks for reporting yet another great feature request! You really help us push our plugins to the next level.
> 
> About the sitemap plugin; we are currently in the process of migrating the plugin to the [Webtools suite](https://github.com/pluginpal/strapi-webtools). Just now I've released the first beta version of the [Webtools Sitemap Addon to NPM](https://www.npmjs.com/package/@pluginpal/webtools-addon-sitemap) It has all the same features you're used to from the standalone Sitemap plugin, but uses the core Webtools plugin for it's URL management.
> 
> The issue you created about the "Ignore all content types..." is a feature that's already integrated in Webtools.
> 
> That being said I would love it if you could give Webtools and the Sitemap addon a try. I think you'll like it a lot.

There are some issues with this, the first, it is not clear if we need to install `core-webtools`, so we installed only the adding and we got the issue:
![image](https://github.com/pluginpal/strapi-plugin-sitemap/assets/5034215/010d4167-6869-48b8-b9ae-e40128c5e631)

This happens when we don't setup the configuration, when we do it, it fails even to load the admin:
```bash
    ~/Projects/Portfolio/backend    PBE-001-strapi-4 !4  yarn develop                                                                              ✔  20s   system  
✔ Cleaning dist dir (10ms)
⠋ Building build context
[INFO] Including the following ENV variables as part of the JS bundle:
    - ADMIN_PATH
    - STRAPI_ADMIN_BACKEND_URL
    - STRAPI_TELEMETRY_DISABLED
✔ Building build context (107ms)
✔ Creating admin (9161ms)
⠙ Loading Strapi[ERROR]  There seems to be an unexpected error, try again with --debug for more information 

┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                                                   │
│   Error: Error loading the plugin sitemap because sitemap is not installed. Please either install the plugin or remove it's configuration.        │
│       at Object.loadPlugins (/home/luisalaguna/Projects/Portfolio/backend/node_modules/@strapi/strapi/dist/core/loaders/plugins/index.js:83:13)   │
│       at async Strapi.loadPlugins (/home/luisalaguna/Projects/Portfolio/backend/node_modules/@strapi/strapi/dist/Strapi.js:311:5)                 │
│       at async Promise.all (index 3)                                                                                                              │
│       at async Strapi.register (/home/luisalaguna/Projects/Portfolio/backend/node_modules/@strapi/strapi/dist/Strapi.js:341:5)                    │
│       at async Strapi.load (/home/luisalaguna/Projects/Portfolio/backend/node_modules/@strapi/strapi/dist/Strapi.js:425:5)                        │
│       at async Object.develop (/home/luisalaguna/Projects/Portfolio/backend/node_modules/@strapi/admin/dist/_chunks/index-sNH2VWbC.js:837:28)     │
│       at async develop (/home/luisalaguna/Projects/Portfolio/backend/node_modules/@strapi/admin/dist/_chunks/develop-YNTGWKMC.js:61:5)            │
│       at async Command.parseAsync (/home/luisalaguna/Projects/Portfolio/backend/node_modules/commander/lib/command.js:923:5)                      │
│       at async Module.runStrapiCommand (/home/luisalaguna/Projects/Portfolio/backend/node_modules/@strapi/strapi/dist/commands/index.js:130:3)    │
│                                                                                                                                                   │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

Installing web tools works fine, but the sitemap cannot be enabled since the config is still broken.

So, it is not usable yet.

I think it is required to update the documentation!

**Comment by SalahAdDin** [comment]
Ok, cool, it seems I was able to setup the sitemap:
```
  webtools: {
    sitemap: {
      enabled: true,
      config: {
        cron: "* * * * 7",
        xsl: true,
        autoGenerate: false,
        caching: true,
      },
    },
  },
  ```
  
  I don't know if it is the right way but at least It does not break the run.
  
  It would be useful to add this to the documentation.

**Comment by SalahAdDin** [comment]
But, it seems there is an issue with the web tools URL patterns screen:
![image](https://github.com/pluginpal/strapi-plugin-sitemap/assets/5034215/eb44010b-7aea-4946-af20-9cc801c7804f)

It never finishes to load, why?

**Comment by boazpoolman** [comment]
Unsure, might be a bug. Please for all of these issues report them on the webtools repo

**Comment by SalahAdDin** [comment]
Opened: https://github.com/pluginpal/strapi-webtools/issues/150
