### ISSUE TITLE
Unwanted tag <script/> in the generated file sitemap.xml

### ISSUE THREAD

**Issue by OlhaZemliakova** [pluginpal/strapi-plugin-sitemap#172]
<img width="1314" alt="Screenshot 2024-06-14 at 4 12 06 PM" src="https://github.com/pluginpal/strapi-plugin-sitemap/assets/106036229/c77e0903-0af1-43f1-9655-5a7f79c260c3">

Hello 👋 in my generated file sitemap.xml I have unnecessary tag <script/>

**Comment by boazpoolman** [comment]
I'm unable to reproduce this issue.
I've tried putting the `xsl` setting to `false`, as it looks like you've done so too.

Please provide us with all your system info, plugin settings and screenshots if applicable.

**Comment by OlhaZemliakova** [comment]
Attached are the screenshots of the settings and configurations.
<img width="804" alt="Screenshot 2024-06-15 at 4 53 48 PM" src="https://github.com/pluginpal/strapi-plugin-sitemap/assets/106036229/55dcc60b-f43c-4a66-9234-862455265945">
<img width="1176" alt="Screenshot 2024-06-15 at 4 56 12 PM" src="https://github.com/pluginpal/strapi-plugin-sitemap/assets/106036229/892d5364-d074-4ccf-a7f7-c8e776841fbd">
<img width="1123" alt="Screenshot 2024-06-15 at 4 56 26 PM" src="https://github.com/pluginpal/strapi-plugin-sitemap/assets/106036229/bd9a6244-cb7b-4690-a63c-eebd513cb909">

**Comment by boazpoolman** [comment]
I’m still unable to reproduce the issue.

Could you setup a minimal example repo with the same config?

**Comment by OlhaZemliakova** [comment]
I identified the cause of the unnecessary <script/> tag. It was triggered by the 'React Developer Tools' extension in my browser. After disabling this extension, the issue disappeared.

**Comment by boazpoolman** [comment]
Allright. Then this issue can be closed.
Thanks for being attentive!
