### ISSUE TITLE
This plugin might generate duplicate content if relational field is not mandatory

### ISSUE THREAD

**Issue by Tyki** [pluginpal/strapi-plugin-sitemap#175]
### Describe the bug

If you add a non mandatory field in the allowedFields, the plugin might generate invalid urls or duplicate content when the field is not filled in Strapi

### Steps to reproduce the behavior

1. Add a "slug" field to allowedFields
2. Create a content in which you dont fill the "slug" property in Strapi (for whatever reason)
3. Generate the sitemap
4. The sitemap generate multiple entries with the same url because of empty slugs

### Expected behavior

Avoid duplicate content and faulty urls by discarding invalid relation fields

### Code snippets

https://github.com/pluginpal/strapi-plugin-sitemap/blob/master/server/services/pattern.js#L125

```
if (!relationalField) {
      pattern = pattern.replace(`[${field}]`, entity[field] || '');
    } else if (Array.isArray(entity[relationalField[0]])) {
      strapi.log.error(logMessage('Something went wrong whilst resolving the pattern.'));
    } else if (typeof entity[relationalField[0]] === 'object') {
      pattern = pattern.replace(`[${field}]`, entity[relationalField[0]] && entity[relationalField[0]][relationalField[1]] ? entity[relationalField[0]][relationalField[1]] : '');
    }
```

The code replace by an empty string if the field is not populated, which lead to duplicate content if the field is not mandatory

### System

- Node.js version: V20.5
- NPM version: 
- Strapi version: 4.13.3
- Plugin version: 3.1.1
- Database: Mysql
- Operating system: Ubuntu

**Comment by boazpoolman** [comment]
This issue has been fixed and released with version [3.2.0](https://github.com/pluginpal/strapi-plugin-sitemap/releases/tag/3.2.0)
