### ISSUE TITLE
Translations are not linked  properly

### ISSUE THREAD

**Issue by vinda2401** [pluginpal/strapi-plugin-sitemap#179]
After an upgrade of the admin panel, switching between translations for records stored in both English (EN) and Dutch (NL) throws an error. The linking between the translations appears to be improperly set.
Steps to reproduce the behavior

1.     Open the admin panel.
2.     Locate and open a record that has translations in both EN and NL.
3.     Attempt to switch between the EN and NL translations.
4.     Observe the error that occurs.

It should have switched between the recods without throwing an error

### Screenshots
![image](https://github.com/user-attachments/assets/1a9c2512-ce3c-46a1-abb2-05eb46dd1490)

### System

- Node.js version: 18+
- NPM version: 18.6
- Strapi version: 5.0.0-rc.8
- Plugin version: 
- Database: mysql
- Operating system: Ubuntu 22.04.4 LTS

**Comment by boazpoolman** [comment]
This plugin is not compatible with the Strapi 5.0.0 release candidates.

**Comment by boazpoolman** [comment]
I'm closing this issue because the plugin doesn't support Strapi 5.
