### ISSUE TITLE
Single types do not show titles correctly

### ISSUE THREAD

**Issue by vinda2401** [pluginpal/strapi-plugin-sitemap#180]
Single types do not show the title properly in edit mode

### Steps to reproduce the behavior

1. Go to Strapi Admin
2. Click on any single type
3. Check the title of the single type (Shown as Untitled as shown in the screenshot)

### Expected behavior

Single types should show their corresponding titles

### Screenshots

![Screenshot from 2024-08-05 17-06-17-1](https://github.com/user-attachments/assets/01d0520d-44bc-4511-bb67-1995afc44cce)

### System

Node.js version: 18+
NPM version: 18.6
Strapi version: 5.0.0-rc.8
Plugin version:
Database: mysql
Operating system: Ubuntu 22.04.4 LTS

**Comment by boazpoolman** [comment]
This plugin is not compatible with the Strapi 5.0.0 release candidates.

**Comment by boazpoolman** [comment]
I'm closing this issue because the plugin doesn't support Strapi 5.

**Comment by maxdzin** [comment]
Hi @boazpoolman,
Is it planned to support Strapi v5?

**Comment by boazpoolman** [comment]
Hi @maxdzin 
We're currently in the process of migrating this plugin to the [Webtools Suite](https://github.com/pluginpal/strapi-webtools). We will migrate it to v5 as part of Webtools and deprecate the standalone Sitemap plugin as you know it.

You can already test the Webtools Sitemap addon in v4, read the docs at https://docs.pluginpal.io/webtools

The Webtools Sitemap addon is just a copy of the standalone plugin, so you'll have all the features you're used to, with extra functionalities like URL management.

**Comment by maxdzin** [comment]
@boazpoolman Thank you for the update and such great work.
I'll try that soon definitely.
It seems worth mentioning that WIP with the link somewhere in README of this repo.

**Comment by boazpoolman** [comment]
@maxdzin That’s a great idea, will do that soon!
